version: '3.8'

services:
  api:
    build: .
    container_name: ia-teddy-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=ia_teddy
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:6.0
    container_name: ia-teddy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 